services:
  nextjs:
    build:
      dockerfile: Dockerfile
    container_name: nextjs_vidhub
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - VIRTUAL_HOST=www.xoailac.top
      - LETSENCRYPT_HOST=www.xoailac.top
      - LETSENCRYPT_EMAIL=ml2673572@gmail.com
      - VIRTUAL_PORT=3000
    networks:
      - app-network
networks:
  app-network:
    external: true
    name: app-network
